[project]
requires-python = ">=3.11"

[tool.ruff]

# default is too small
line-length = 100
target-version = "py311"

[tool.ruff.lint]

# E: pycode style (error)
# W: pycode style (warning)
# F: Pyflakes
# I: ishort
# ANN: type annotations
# D: docstrings

select = ["E", "F", "I", "ANN", "D", "W"]

[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ruff.format]

quote-style = "double"
indent-style = "space"
