name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        uses: astral-sh/setup-uv@v1
      - run: uv pip install -e .[dev]

      - name: Lint and format check with ruff
        run: |
          ruff check .
          ruff format --check .
